// src/GraphData.js

export const graphData = {
  vertices: [
    { id: 'Program' },
    { id: 'TUI' },
    { id: 'Car' },
    { id: 'CarExistException' },
    { id: 'ClientInfo' },
    { id: 'CreatingObject' },
    { id: 'ElectricMotor' },
    { id: 'fillEnergyToMaxException' },
    { id: 'GarageManager' },
    { id: 'GasMotor' },
    { id: 'MotorBike' },
    { id: 'MotorType' },
    { id: 'Track' },
    { id: 'ValueOutOfRangeException' },
    { id: 'Vehicle' },
    { id: 'Wheels' },
  ],
  edges: [
    { from: 'TUI', to: 'GarageManager' },
    { from: 'TUI', to: 'CreatingObject' },
    { from: 'Car', to: 'Vehicle' },
    { from: 'ClientInfo', to: 'Vehicle' },
    { from: 'CreatingObject', to: 'Vehicle' },
    { from: 'CreatingObject', to: 'GarageManager' },
    { from: 'ElectricMotor', to: 'MotorType' },
    { from: 'GarageManager', to: 'ClientInfo' },
    { from: 'GarageManager', to: 'Vehicle' },
    { from: 'GasMotor', to: 'MotorType' },
    { from: 'MotorBike', to: 'Vehicle' },
    { from: 'Track', to: 'Vehicle' },
    { from: 'Vehicle', to: 'MotorType' },
    { from: 'Vehicle', to: 'Wheels' },
  ],
};
